before_script:
 - echo "Execute scripts which are required to bootstrap the application. !"

after_script:
 - echo "Clean up activity can be done here !."
 
cache:
 paths:
 - /root/.m2/repository
 
stages:
 - build
 - test
 - deploy

build:
 stage: build
 image: maven:3.3.9-jdk-8
 script:
 - mvn clean package
 tags:
 - shared

test:
 stage: test
 image: maven:3.3.9-jdk-8
 script:
 - mvn test
 tags:
 - shared
 
deploy:
 stage: deploy
 image: ruby:2.3
 script:
 - apt-get update -qy
 - apt-get install -y ruby-dev
 - gem install dpl
 - dpl --provider=heroku --app=springboot-devops-gitlab --api-key=$HEROKU_API_KEY
 environment:
 # name: dev
 # url: https://springboot-devops-gitlab.herokuapp.com
 only:
 - master
 tags:
 - shared
