before_script:
 - echo "Execute scripts which are required to bootstrap the application. !"

after_script:
 - echo "Clean up activity can be done here !."
 
cache:
 paths:
 - /root/.m2/repository
 
stages:
 - test
 - build
 - deploy

test:
 stage: test
 image: maven:3.3.9-jdk-8
 script:
 - mvn test

build:
 stage: build
 image: maven:3.3.9-jdk-8
 script:
 - mvn clean package

deploy_dev:
 stage: deploy
 image: ruby:2.3
 script:
 - apt-get update -qy
 - apt-get install -y ruby-dev
 - gem install dpl
 - dpl --provider=heroku --app=dev-springboot-devops-gitlab --api-key=$HEROKU_API_KEY
 environment:
  name: development
  url: https://dev-springboot-devops-gitlab.herokuapp.com
 only:
 - master

deploy_staging:
 stage: deploy
 image: ruby:2.3
 script:
 - apt-get update -qy
 - apt-get install -y ruby-dev
 - gem install dpl
 - dpl --provider=heroku --app=stage-springboot-devops-gitlab --api-key=$HEROKU_API_KEY
 environment:
  name: staging
  url: https://stage-springboot-devops-gitlab.herokuapp.com
 only:
 - master

 deploy_prod:
 stage: deploy
 image: ruby:2.3
 script:
 - apt-get update -qy
 - apt-get install -y ruby-dev
 - gem install dpl
 - dpl --provider=heroku --app=springboot-devops-gitlab --api-key=$HEROKU_API_KEY
 environment:
  name: production
  url: https://springboot-devops-gitlab.herokuapp.com
 when: manual
 only:
 - master
 

